#pragma once
// CPU-side mesh representation shared by the OBJ importer, brush compiler
// (Hammer-mode geometry -> renderable mesh), and lightmap UV unwrapper. The
// GPU-side vertex/index buffers (D3D11) are built from this in
// engine/asset/GpuMeshCache.

#include "engine/core/Base.h"
#include "engine/math/Math.h"
#include <vector>
#include <string>

namespace fw {

struct Vertex {
    vec3 position{0.0f};
    vec3 normal{0, 1, 0};
    vec3 tangent{1, 0, 0};
    vec2 uv0{0.0f};      // material UVs
    vec2 uv1{0.0f};      // lightmap UVs (generated by the lightmap unwrapper)
    vec4 color{1.0f};
};

struct SubMesh {
    u32 indexStart = 0;
    u32 indexCount = 0;
    i32 materialIndex = 0;
};

struct MeshData {
    std::vector<Vertex> vertices;
    std::vector<u32> indices;
    std::vector<SubMesh> subMeshes;
    std::vector<std::string> materialSlotNames; // names only; actual material assets referenced by MeshRendererComponent
    AABB bounds;

    void RecalculateBounds();
    void RecalculateNormals();
    void RecalculateTangents();

    // Very simple axis-projection lightmap UV generation (box-projects each
    // triangle onto the dominant axis and packs into an atlas grid). Good
    // enough for a baked-lighting pipeline without pulling in a full UV
    // unwrapper library.
    void GenerateLightmapUVs(int atlasResolution = 512);

    static bool LoadOBJ(const std::string& path, MeshData& out, std::string* outError = nullptr);
    static bool SaveFWMesh(const std::string& path, const MeshData& mesh);
    static bool LoadFWMesh(const std::string& path, MeshData& out);

    // Simple primitive builders, used by the editor's "Add primitive" menu
    // and by the brush compiler as a fallback.
    static MeshData CreateBox(const vec3& halfExtents);
    static MeshData CreateSphere(float radius, int segments = 24);
    static MeshData CreatePlane(float sizeX, float sizeZ, int subdivisions = 1);
    static MeshData CreateCylinder(float radius, float height, int segments = 24);
};

} // namespace fw
